// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeopleDirectory.Infrastructure.Data;

#nullable disable

namespace PeopleDirectory.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PeopleDirectory.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ChangesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("PeopleDirectory.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "Cape Town"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Name = "Johannesburg"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            Name = "Durban"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 1,
                            Name = "Pretoria"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 2,
                            Name = "New York"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 2,
                            Name = "Los Angeles"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 2,
                            Name = "Chicago"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 2,
                            Name = "Houston"
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 3,
                            Name = "London"
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 3,
                            Name = "Manchester"
                        },
                        new
                        {
                            Id = 11,
                            CountryId = 3,
                            Name = "Birmingham"
                        },
                        new
                        {
                            Id = 12,
                            CountryId = 4,
                            Name = "Sydney"
                        },
                        new
                        {
                            Id = 13,
                            CountryId = 4,
                            Name = "Melbourne"
                        },
                        new
                        {
                            Id = 14,
                            CountryId = 4,
                            Name = "Brisbane"
                        },
                        new
                        {
                            Id = 15,
                            CountryId = 5,
                            Name = "Toronto"
                        },
                        new
                        {
                            Id = 16,
                            CountryId = 5,
                            Name = "Vancouver"
                        },
                        new
                        {
                            Id = 17,
                            CountryId = 5,
                            Name = "Montreal"
                        },
                        new
                        {
                            Id = 18,
                            CountryId = 6,
                            Name = "Berlin"
                        },
                        new
                        {
                            Id = 19,
                            CountryId = 6,
                            Name = "Munich"
                        },
                        new
                        {
                            Id = 20,
                            CountryId = 7,
                            Name = "Mumbai"
                        },
                        new
                        {
                            Id = 21,
                            CountryId = 7,
                            Name = "Delhi"
                        },
                        new
                        {
                            Id = 22,
                            CountryId = 7,
                            Name = "Bangalore"
                        },
                        new
                        {
                            Id = 23,
                            CountryId = 8,
                            Name = "São Paulo"
                        },
                        new
                        {
                            Id = 24,
                            CountryId = 8,
                            Name = "Rio de Janeiro"
                        },
                        new
                        {
                            Id = 25,
                            CountryId = 9,
                            Name = "Tokyo"
                        },
                        new
                        {
                            Id = 26,
                            CountryId = 9,
                            Name = "Osaka"
                        },
                        new
                        {
                            Id = 27,
                            CountryId = 10,
                            Name = "Paris"
                        },
                        new
                        {
                            Id = 28,
                            CountryId = 10,
                            Name = "Lyon"
                        });
                });

            modelBuilder.Entity("PeopleDirectory.Domain.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ZA",
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 2,
                            Code = "US",
                            Name = "United States"
                        },
                        new
                        {
                            Id = 3,
                            Code = "GB",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 4,
                            Code = "AU",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 5,
                            Code = "CA",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 6,
                            Code = "DE",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 7,
                            Code = "IN",
                            Name = "India"
                        },
                        new
                        {
                            Id = 8,
                            Code = "BR",
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 9,
                            Code = "JP",
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 10,
                            Code = "FR",
                            Name = "France"
                        });
                });

            modelBuilder.Entity("PeopleDirectory.Domain.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FirstName");

                    b.HasIndex("LastName");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressLine = "123 Long Street",
                            CityId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1990, 5, 15),
                            Email = "mark.johnson@example.com",
                            FirstName = "Mark",
                            Gender = "Male",
                            IsActive = true,
                            LastName = "Johnson",
                            MobileNumber = "+27821234567",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            AddressLine = "456 Main Road",
                            CityId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1985, 8, 22),
                            Email = "sarah.williams@example.com",
                            FirstName = "Sarah",
                            Gender = "Female",
                            IsActive = true,
                            LastName = "Williams",
                            MobileNumber = "+27829876543",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            AddressLine = "789 Broadway",
                            CityId = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1992, 3, 10),
                            Email = "james.smith@example.com",
                            FirstName = "James",
                            Gender = "Male",
                            IsActive = true,
                            LastName = "Smith",
                            MobileNumber = "+12125551234",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            AddressLine = "10 Baker Street",
                            CityId = 9,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1988, 11, 30),
                            Email = "emily.brown@example.com",
                            FirstName = "Emily",
                            Gender = "Female",
                            IsActive = true,
                            LastName = "Brown",
                            MobileNumber = "+447911123456",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            AddressLine = "55 George Street",
                            CityId = 12,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1995, 7, 4),
                            Email = "michael.davis@example.com",
                            FirstName = "Michael",
                            Gender = "Male",
                            IsActive = true,
                            LastName = "Davis",
                            MobileNumber = "+61412345678",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            AddressLine = "100 Queen Street",
                            CityId = 15,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1993, 2, 14),
                            Email = "jessica.wilson@example.com",
                            FirstName = "Jessica",
                            Gender = "Female",
                            IsActive = true,
                            LastName = "Wilson",
                            MobileNumber = "+14161234567",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            AddressLine = "22 Unter den Linden",
                            CityId = 18,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1987, 9, 25),
                            Email = "david.taylor@example.com",
                            FirstName = "David",
                            Gender = "Male",
                            IsActive = true,
                            LastName = "Taylor",
                            MobileNumber = "+493012345678",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            AddressLine = "15 Marine Drive",
                            CityId = 20,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1991, 12, 3),
                            Email = "priya.sharma@example.com",
                            FirstName = "Priya",
                            Gender = "Female",
                            IsActive = true,
                            LastName = "Sharma",
                            MobileNumber = "+919876543210",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            AddressLine = "Av. Paulista 1000",
                            CityId = 23,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1994, 6, 18),
                            Email = "lucas.silva@example.com",
                            FirstName = "Lucas",
                            Gender = "Male",
                            IsActive = true,
                            LastName = "Silva",
                            MobileNumber = "+5511987654321",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            AddressLine = "3-1 Shibuya",
                            CityId = 25,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1996, 4, 7),
                            Email = "yuki.tanaka@example.com",
                            FirstName = "Yuki",
                            Gender = "Female",
                            IsActive = true,
                            LastName = "Tanaka",
                            MobileNumber = "+81312345678",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            AddressLine = "8 Rue de Rivoli",
                            CityId = 27,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1989, 1, 20),
                            Email = "sophie.dupont@example.com",
                            FirstName = "Sophie",
                            Gender = "Female",
                            IsActive = true,
                            LastName = "Dupont",
                            MobileNumber = "+33612345678",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            AddressLine = "45 Kloof Street",
                            CityId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1986, 10, 12),
                            Email = "mark.vdberg@example.com",
                            FirstName = "Mark",
                            Gender = "Male",
                            IsActive = true,
                            LastName = "van der Berg",
                            MobileNumber = "+27831112233",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            AddressLine = "321 Sunset Blvd",
                            CityId = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1997, 3, 28),
                            Email = "olivia.martinez@example.com",
                            FirstName = "Olivia",
                            Gender = "Female",
                            IsActive = true,
                            LastName = "Martinez",
                            MobileNumber = "+12135557890",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            AddressLine = "100 MG Road",
                            CityId = 22,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1990, 8, 5),
                            Email = "raj.patel@example.com",
                            FirstName = "Raj",
                            Gender = "Male",
                            IsActive = true,
                            LastName = "Patel",
                            MobileNumber = "+919123456789",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            AddressLine = "5 Deansgate",
                            CityId = 10,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1992, 5, 30),
                            Email = "emma.thompson@example.com",
                            FirstName = "Emma",
                            Gender = "Female",
                            IsActive = true,
                            LastName = "Thompson",
                            MobileNumber = "+447922987654",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 16,
                            AddressLine = "88 Collins Street",
                            CityId = 13,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1988, 7, 14),
                            Email = "liam.obrien@example.com",
                            FirstName = "Liam",
                            Gender = "Male",
                            IsActive = true,
                            LastName = "O'Brien",
                            MobileNumber = "+61423456789",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 17,
                            AddressLine = "Rua Copacabana 50",
                            CityId = 24,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1995, 11, 2),
                            Email = "ana.costa@example.com",
                            FirstName = "Ana",
                            Gender = "Female",
                            IsActive = true,
                            LastName = "Costa",
                            MobileNumber = "+5521912345678",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 18,
                            AddressLine = "15 Marienplatz",
                            CityId = 19,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1984, 4, 19),
                            Email = "thomas.mueller@example.com",
                            FirstName = "Thomas",
                            Gender = "Male",
                            IsActive = true,
                            LastName = "Mueller",
                            MobileNumber = "+498912345678",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 19,
                            AddressLine = "200 Robson Street",
                            CityId = 16,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1993, 9, 8),
                            Email = "chloe.nguyen@example.com",
                            FirstName = "Chloe",
                            Gender = "Female",
                            IsActive = true,
                            LastName = "Nguyen",
                            MobileNumber = "+16041234567",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 20,
                            AddressLine = "78 Florida Road",
                            CityId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1991, 2, 27),
                            Email = "sipho.nkosi@example.com",
                            FirstName = "Sipho",
                            Gender = "Male",
                            IsActive = true,
                            LastName = "Nkosi",
                            MobileNumber = "+27841234567",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PeopleDirectory.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("PeopleDirectory.Domain.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PeopleDirectory.Domain.Entities.City", b =>
                {
                    b.HasOne("PeopleDirectory.Domain.Entities.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("PeopleDirectory.Domain.Entities.Person", b =>
                {
                    b.HasOne("PeopleDirectory.Domain.Entities.City", "City")
                        .WithMany("People")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("PeopleDirectory.Domain.Entities.City", b =>
                {
                    b.Navigation("People");
                });

            modelBuilder.Entity("PeopleDirectory.Domain.Entities.Country", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
